# Generated by Django 2.1.5 on 2020-02-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='salary',
            field=models.CharField(default=120, max_length=12),
        ),
    ]
